'use client';

import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeft, Check, FileText, Plus, Save, Trash2 } from 'lucide-react';
import Link from 'next/link';
import type { DocumentItem, NormalizedDocumentData, InvoiceData } from '@/lib/documents/types';

const fallbackDocument: NormalizedDocumentData = {
  id: 'demo-invoice', type: 'invoice', confidence: 0.96, sourceFile: { name: 'invoice.pdf', type: 'application/pdf' },
  data: { invoiceNumber: 'INV-1001', invoiceDate: '2026-09-23', dueDate: '2026-10-07', currency: 'USD', seller: { name: 'ABC Trading Ltd', email: 'billing@abctrading.example', address: '18 Market Street, New York' }, customer: { name: 'Northwind Retail', email: 'accounts@northwind.example', address: '44 Harbor Road, Boston' }, items: [{ id: 'item-1', description: 'Product package', quantity: 10, unitPrice: 20, discount: 0, taxRate: 10 }], notes: 'Thank you for your business.', terms: 'Payment due within 14 days.' },
  metadata: { createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
};

const money = (value: number, currency = 'USD') => new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(value);
const itemTotal = (item: DocumentItem) => item.quantity * item.unitPrice * (1 - item.discount / 100);

export default function EditorPage() {
  const [document, setDocument] = useState(fallbackDocument);
  const [saved, setSaved] = useState(true);
  const [previewTab, setPreviewTab] = useState<'edit' | 'preview'>('edit');

  useEffect(() => {
    const id = new URLSearchParams(window.location.search).get('id');
    const stored = id ? window.sessionStorage.getItem(`document:${id}`) : null;
    if (stored) setDocument(JSON.parse(stored) as NormalizedDocumentData);
  }, []);

  const data = document.data as unknown as InvoiceData;
  const subtotal = useMemo(() => data.items.reduce((sum, item) => sum + itemTotal(item), 0), [data.items]);
  const tax = useMemo(() => data.items.reduce((sum, item) => sum + itemTotal(item) * item.taxRate / 100, 0), [data.items]);
  const total = subtotal + tax;
  const updateData = (nextData: InvoiceData) => { setDocument({ ...document, data: { ...nextData }, metadata: { ...document.metadata, updatedAt: new Date().toISOString() } }); setSaved(false); };
  const updateItem = (index: number, patch: Partial<DocumentItem>) => updateData({ ...data, items: data.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) });
  const saveDraft = () => { window.sessionStorage.setItem(`document:${document.id}`, JSON.stringify(document)); setSaved(true); };

  return <main className="min-h-screen bg-slate-50 px-4 py-6 md:py-8"><div className="mx-auto max-w-7xl">
    <Link href="/upload" className="mb-5 inline-flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-slate-900"><ArrowLeft className="h-4 w-4" />Back to upload</Link>
    <header className="mb-6 flex flex-col gap-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-600">Extraction review</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Edit {document.sourceFile.name}</h1><p className="mt-2 text-sm text-slate-500">{Math.round(document.confidence * 100)}% confidence · Changes calculate automatically</p></div><div className="flex flex-wrap items-center gap-3"><span className="text-sm text-slate-500">{saved ? 'All changes saved' : 'Unsaved changes'}</span><button type="button" onClick={saveDraft} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700"><Save className="h-4 w-4" />Save draft</button><Link href="/templates" className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Choose template</Link></div></header>
    <div className="mb-4 grid grid-cols-2 rounded-xl border border-slate-200 bg-white p-1 md:hidden"><button type="button" onClick={() => setPreviewTab('edit')} className={`rounded-lg px-3 py-2 text-sm font-semibold ${previewTab === 'edit' ? 'bg-slate-900 text-white' : 'text-slate-600'}`}>Edit</button><button type="button" onClick={() => setPreviewTab('preview')} className={`rounded-lg px-3 py-2 text-sm font-semibold ${previewTab === 'preview' ? 'bg-slate-900 text-white' : 'text-slate-600'}`}>Preview</button></div>
    <div className="grid gap-6 xl:grid-cols-[1fr_0.9fr]"><section className={`${previewTab === 'preview' ? 'hidden md:block' : ''} space-y-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm`}>
      <div className="flex items-center justify-between rounded-2xl border border-blue-100 bg-blue-50 p-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-600">Document detected</p><p className="mt-1 text-2xl font-bold capitalize text-slate-900">{document.type.replace('_', ' ')}</p></div><span className="rounded-full bg-white px-3 py-1.5 text-sm font-semibold text-blue-700">{Math.round(document.confidence * 100)}%</span></div>
      <div><h2 className="mb-4 text-lg font-semibold text-slate-900">Invoice information</h2><div className="grid gap-4 md:grid-cols-3">{([['invoiceNumber', 'Invoice number'], ['invoiceDate', 'Issue date'], ['dueDate', 'Due date']] as const).map(([key, label]) => <label key={key} className="space-y-2"><span className="text-sm font-medium text-slate-700">{label}</span><input type={key === 'invoiceNumber' ? 'text' : 'date'} value={data[key]} onChange={(event) => updateData({ ...data, [key]: event.target.value })} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-slate-900" /></label>)}</div></div>
      <div className="grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-sm font-medium text-slate-700">Seller</span><input value={data.seller.name} onChange={(event) => updateData({ ...data, seller: { ...data.seller, name: event.target.value } })} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-slate-900" /></label><label className="space-y-2"><span className="text-sm font-medium text-slate-700">Customer</span><input value={data.customer.name} onChange={(event) => updateData({ ...data, customer: { ...data.customer, name: event.target.value } })} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-slate-900" /></label></div>
      <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold text-slate-900">Line items</h2><p className="text-sm text-slate-500">Totals are calculated from numeric fields.</p></div><button type="button" onClick={() => updateData({ ...data, items: [...data.items, { id: `item-${Date.now()}`, description: 'New item', quantity: 1, unitPrice: 0, discount: 0, taxRate: 10 }] })} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-3 py-2 text-xs font-semibold text-white"><Plus className="h-3.5 w-3.5" />Add item</button></div><div className="space-y-3">{data.items.map((item, index) => <div key={item.id} className="grid gap-3 rounded-xl border border-slate-200 bg-white p-3 md:grid-cols-[2fr_0.7fr_0.9fr_0.7fr_auto]"><input aria-label="Item description" value={item.description} onChange={(event) => updateItem(index, { description: event.target.value })} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900" /><input aria-label="Quantity" type="number" min="0" value={item.quantity} onChange={(event) => updateItem(index, { quantity: Number(event.target.value) })} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900" /><input aria-label="Unit price" type="number" min="0" step="0.01" value={item.unitPrice} onChange={(event) => updateItem(index, { unitPrice: Number(event.target.value) })} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900" /><input aria-label="Tax rate" type="number" min="0" value={item.taxRate} onChange={(event) => updateItem(index, { taxRate: Number(event.target.value) })} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900" /><button type="button" aria-label={`Remove ${item.description}`} onClick={() => updateData({ ...data, items: data.items.filter((_, itemIndex) => itemIndex !== index) })} className="flex h-10 items-center justify-center rounded-lg border border-slate-200 px-3 text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div>)}</div></div>
      <label className="block space-y-2"><span className="text-sm font-medium text-slate-700">Notes</span><textarea value={data.notes} onChange={(event) => updateData({ ...data, notes: event.target.value })} className="min-h-24 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-slate-900" /></label>
    </section><aside className={`${previewTab === 'edit' ? 'hidden md:block' : ''} space-y-6`}><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2 text-slate-900"><FileText className="h-5 w-5" /><span className="font-semibold">Live preview</span></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">Updated</span></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-start justify-between border-b border-slate-200 pb-5"><div><p className="text-sm font-semibold text-blue-600">{data.seller.name}</p><p className="mt-1 text-2xl font-bold text-slate-900">INVOICE</p></div><div className="text-right text-sm text-slate-500"><p>#{data.invoiceNumber}</p><p>{data.invoiceDate}</p></div></div><div className="py-5 text-sm"><p className="text-xs uppercase tracking-wider text-slate-400">Billed to</p><p className="mt-1 font-semibold text-slate-900">{data.customer.name}</p><p className="text-slate-500">{data.customer.address}</p></div><div className="space-y-3 border-t border-slate-200 pt-4 text-sm">{data.items.map((item) => <div key={item.id} className="flex justify-between gap-3"><span className="text-slate-600">{item.description} × {item.quantity}</span><span className="font-medium text-slate-900">{money(itemTotal(item))}</span></div>)}<div className="flex justify-between border-t border-slate-200 pt-3 text-slate-600"><span>Subtotal</span><span>{money(subtotal)}</span></div><div className="flex justify-between text-slate-600"><span>Tax</span><span>{money(tax)}</span></div><div className="flex justify-between border-t border-slate-200 pt-3 text-base font-bold text-slate-900"><span>Total</span><span>{money(total, data.currency)}</span></div></div></div></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Validation</p><div className="mt-4 space-y-3">{[['Seller name', Boolean(data.seller.name)], ['Invoice number', Boolean(data.invoiceNumber)], ['Line items', data.items.length > 0]].map(([label, valid]) => <div key={String(label)} className="flex items-center justify-between rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-700"><span>{label}</span><span className={`inline-flex h-6 w-6 items-center justify-center rounded-full ${valid ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{valid ? <Check className="h-4 w-4" /> : <AlertTriangle className="h-4 w-4" />}</span></div>)}<div className="flex items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-700"><AlertTriangle className="h-4 w-4 shrink-0" />Review extracted values before exporting.</div></div></div></aside></div>
  </div></main>;
}
